import 'package:flutter/material.dart';
import 'screens/signup_page.dart'; // LoginPage 클래스 임포트
import 'package:google_fonts/google_fonts.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    // Get the screen size
    final Size screenSize = MediaQuery.of(context).size;

    return MaterialApp(
      theme: ThemeData(
        textTheme:
            GoogleFonts.gaeguTextTheme(), // Apply the font to the entire theme
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: SingleChildScrollView(
          // SingleChildScrollView로 변경
          child: SignUp(screenSize: screenSize),
        ),
      ),
      routes: {
        '/signup': (context) => SignUpPage(), // 로그인 페이지 경로 추가
      },
    );
  }
}

class SignUp extends StatelessWidget {
  final Size screenSize;

  const SignUp({super.key, required this.screenSize});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: screenSize
              .width, // 화면 너비에 맞게 조정 Adjust width based on screen size
          height: screenSize
              .height, // 화면 높이에 맞게 조정 Adjust height based on screen size
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: const Color(0xFFEFB411)),
          child: Stack(
            children: [
              Positioned(
                left: 1,
                top: screenSize.height / 2 -
                    214, // 화면의 중간에서 위로 214만큼 위로 이동 Move 214 pixels up from the center of the screen
                child: Center(
                  child: Container(
                    padding: const EdgeInsets.symmetric(horizontal: 24),
                    child: GestureDetector(
                      onTap: () {
                        Navigator.pushNamed(
                            context, '/signup'); // 클릭 시 로그인 페이지로 이동
                      },
                      child: const Text('SignUp',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                              fontSize: 70,
                              fontWeight: FontWeight
                                  .bold)), // 여기에 텍스트 위젯 추가 Add your text widget here
                    ),
                  ),
                ),
              ),
              // 다른 Positioned 위젯들을 여기에 추가 Add other Positioned widgets here
            ],
          ),
        ),
      ],
    );
  }
}
